### ISSUE TITLE
Security Issue Disclosure - Request for Private Communication

### ISSUE THREAD

**Issue by Roni-Carta** [stevemao/html-comment-regex#5]
Hello,

I have identified a potential security vulnerability in the project and would like to discuss it privately to avoid public disclosure. Could you please provide a channel for communication, such as an email address or other means, to share the details confidentially?

Thank you for your time and consideration. Looking forward to your response.

Cheers ! 

Roni

**Comment by stevemao** [comment]
Is it possible to create a PR? 

I'm not actively maintaining this repo so alternatively I can add someone as admin. thanks

**Comment by Roni-Carta** [comment]
Hi @stevemao, 

Thanks for letting me know. Is it possible to just shout an email explaining the situation ? It's an issue that doesn't need a PR to get fixed. Thanks for your time again. 

Cheers !

**Comment by stevemao** [comment]
please send it to my GitHub email

**Comment by Roni-Carta** [comment]
Thanks @stevemao. I've just sent the email. Can you confirm that you received it ? :D 

Cheers !

**Comment by stevemao** [comment]
I have just replied you.

Thanks a lot!
